# Generated by Django 4.2.3 on 2023-07-22 16:36

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historytransfer',
            options={'verbose_name': 'История переводов', 'verbose_name_plural': 'История переводов'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.CharField(blank=True, default=0, max_length=255, null=True, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_adress',
            field=models.CharField(default=users.models.generate_wallet_address, max_length=12, verbose_name='Уникальный кошелек'),
        ),
    ]
