# Generated by Django 4.2.3 on 2023-07-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_historytransfer_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryTransfer',
        ),
    ]
